AWSTemplateFormatVersion: 2010-09-09
Description: Infrastructure for Lead From Here app

Parameters:
  DeploymentBucketName:
    Type: String
    Description: Name for the S3 deployment bucket (must be globally unique)

  EBApplicationName:
    Type: String
    Description: Name for the Elastic Beanstalk application

  EBEnvironmentName:
    Type: String
    Description: Name for the Elastic Beanstalk environment

  PlatformVersion:
    Type: String
    Default: "64bit Amazon Linux 2023 v6.7.4 running Node.js 20"
    Description: Elastic Beanstalk Node.js platform version (update when AWS releases new versions)

Resources:
  # S3 Bucket for deployments
  DeploymentBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Ref DeploymentBucketName
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: AES256
      VersioningConfiguration:
        Status: Enabled

  # IAM Role used by the EB service for health reporting and lifecycle management
  EBServiceRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub ${EBApplicationName}-service-role
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Service: elasticbeanstalk.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSElasticBeanstalkEnhancedHealth
        - arn:aws:iam::aws:policy/service-role/AWSElasticBeanstalkService
      Policies:
        - PolicyName: EBServiceRoleEC2Images
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Effect: Allow
                Action: ec2:DescribeImages
                Resource: '*'

  # IAM Role assigned to EC2 instances via instance profile
  EBInstanceProfileRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub ${EBApplicationName}-instance-role
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Service: ec2.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AWSElasticBeanstalkWebTier

  EBInstanceProfile:
    Type: AWS::IAM::InstanceProfile
    Properties:
      InstanceProfileName: !Sub ${EBApplicationName}-instance-profile
      Roles:
        - !Ref EBInstanceProfileRole

  # Elastic Beanstalk Application
  EBApplication:
    Type: AWS::ElasticBeanstalk::Application
    Properties:
      ApplicationName: !Ref EBApplicationName
      Description: Lead From Here - Real-time voting app
      ResourceLifecycleConfig:
        ServiceRole: !GetAtt EBServiceRole.Arn
        VersionLifecycleConfig:
          MaxCountRule:
            Enabled: true
            MaxCount: 20
            DeleteSourceFromS3: true

  # Elastic Beanstalk Environment
  EBEnvironment:
    Type: AWS::ElasticBeanstalk::Environment
    Properties:
      EnvironmentName: !Ref EBEnvironmentName
      ApplicationName: !Ref EBApplication
      SolutionStackName: !Ref PlatformVersion
      OptionSettings:
        # Environment variables
        - Namespace: aws:elasticbeanstalk:application:environment
          OptionName: NODE_ENV
          Value: production
        # Instance type (current-generation, free-tier eligible)
        - Namespace: aws:ec2:instances
          OptionName: InstanceTypes
          Value: t3.micro
        # Instance profile for EC2 instances
        - Namespace: aws:autoscaling:launchconfiguration
          OptionName: IamInstanceProfile
          Value: !Ref EBInstanceProfile
        # Single instance — no load balancer provisioned (suitable for a workshop tool)
        - Namespace: aws:elasticbeanstalk:environment
          OptionName: EnvironmentType
          Value: SingleInstance
        # Service role for health reporting and lifecycle management
        - Namespace: aws:elasticbeanstalk:environment
          OptionName: ServiceRole
          Value: !GetAtt EBServiceRole.Arn
        # Health check against the API so EB confirms the app is running
        - Namespace: aws:elasticbeanstalk:application
          OptionName: Application Healthcheck URL
          Value: /api/state
        - Namespace: aws:elasticbeanstalk:healthreporting:system
          OptionName: HealthCheckSuccessThreshold
          Value: Ok

Outputs:
  DeploymentBucketName:
    Description: Name of the S3 deployment bucket
    Value: !Ref DeploymentBucketName
    Export:
      Name: !Sub ${AWS::StackName}-DeploymentBucket

  EBEnvironmentUrl:
    Description: URL of the Elastic Beanstalk environment
    Value: !GetAtt EBEnvironment.EndpointURL
    Export:
      Name: !Sub ${AWS::StackName}-EBEnvironmentUrl

  EBInstanceProfileName:
    Description: Name of the EC2 instance profile
    Value: !Ref EBInstanceProfile
    Export:
      Name: !Sub ${AWS::StackName}-InstanceProfile
