AWSTemplateFormatVersion: 2010-09-09
Description: GitHub OIDC Provider and IAM Role for GitHub Actions

Parameters:
  GitHubOwner:
    Type: String
    Description: GitHub organization or username

  GitHubRepo:
    Type: String
    Description: GitHub repository name

  RoleName:
    Type: String
    Description: Name for the IAM role

  StackName:
    Type: String
    Description: CloudFormation stack name (for resource limits)

  AWSRegion:
    Type: String
    Description: AWS region

  S3BucketName:
    Type: String
    Description: Name of the S3 deployment bucket

  EBApplicationName:
    Type: String
    Description: Name of the Elastic Beanstalk application

  EBEnvironmentName:
    Type: String
    Description: Name of the Elastic Beanstalk environment

Resources:
  # GitHub OIDC Provider
  # ThumbprintList contains the public TLS certificate thumbprint for
  # token.actions.githubusercontent.com — this is a well-known public value.
  GitHubOIDCProvider:
    Type: AWS::IAM::OIDCProvider
    DeletionPolicy: Retain
    Properties:
      Url: https://token.actions.githubusercontent.com
      ClientIdList:
        - sts.amazonaws.com
      ThumbprintList:
        - 6938FD4D98BABEC356DA5494E410BCB82C2AD4A6

  # IAM Role for GitHub Actions OIDC
  GitHubDeployRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Ref RoleName
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Federated: !GetAtt GitHubOIDCProvider.Arn
            Action: sts:AssumeRoleWithWebIdentity
            Condition:
              # StringEquals (not StringLike) restricts to main branch only —
              # feature branches and PRs cannot assume this role.
              StringEquals:
                token.actions.githubusercontent.com:sub: !Sub repo:${GitHubOwner}/${GitHubRepo}:ref:refs/heads/main
                token.actions.githubusercontent.com:aud: sts.amazonaws.com

  # Broad permissions for GitHub Actions role — scope these down once deployment is working
  GitHubDeployPolicy:
    Type: AWS::IAM::Policy
    Properties:
      PolicyName: !Sub ${RoleName}-DeployPolicy
      PolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Action:
              - elasticbeanstalk:*
              - s3:*
              - cloudformation:*
              - iam:PassRole
              - iam:CreateServiceLinkedRole
            Resource: "*"
      Roles:
        - !Ref GitHubDeployRole

  # Dedicated execution role that CloudFormation assumes when deploying the
  # infrastructure stack.
  CFNExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub ${RoleName}-cfn-execution
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Service: cloudformation.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AdministratorAccess

Outputs:
  GitHubRoleArn:
    Description: ARN of the GitHub Actions role
    Value: !GetAtt GitHubDeployRole.Arn
    Export:
      Name: !Sub ${AWS::StackName}-GitHubRoleArn

  CFNExecutionRoleArn:
    Description: ARN of the CloudFormation execution role (store as AWS_CFN_EXECUTION_ROLE_ARN secret)
    Value: !GetAtt CFNExecutionRole.Arn
    Export:
      Name: !Sub ${AWS::StackName}-CFNExecutionRoleArn
