AWSTemplateFormatVersion: 2010-09-09
Description: GitHub OIDC Provider and IAM Role for GitHub Actions

Parameters:
  GitHubOwner:
    Type: String
    Description: GitHub organization or username

  GitHubRepo:
    Type: String
    Description: GitHub repository name

  RoleName:
    Type: String
    Description: Name for the IAM role

  StackName:
    Type: String
    Description: CloudFormation stack name (for resource limits)

  AWSRegion:
    Type: String
    Description: AWS region

  S3BucketName:
    Type: String
    Description: Name of the S3 deployment bucket

  EBApplicationName:
    Type: String
    Description: Name of the Elastic Beanstalk application

  EBEnvironmentName:
    Type: String
    Description: Name of the Elastic Beanstalk environment

Resources:
  # GitHub OIDC Provider
  # ThumbprintList contains the public TLS certificate thumbprint for
  # token.actions.githubusercontent.com — this is a well-known public value.
  GitHubOIDCProvider:
    Type: AWS::IAM::OIDCProvider
    DeletionPolicy: Retain
    Properties:
      Url: https://token.actions.githubusercontent.com
      ClientIdList:
        - sts.amazonaws.com
      ThumbprintList:
        - 6938FD4D98BABEC356DA5494E410BCB82C2AD4A6

  # IAM Role for GitHub Actions OIDC
  GitHubDeployRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Ref RoleName
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Federated: !GetAtt GitHubOIDCProvider.Arn
            Action: sts:AssumeRoleWithWebIdentity
            Condition:
              # StringEquals (not StringLike) restricts to main branch only —
              # feature branches and PRs cannot assume this role.
              StringEquals:
                token.actions.githubusercontent.com:sub: !Sub repo:${GitHubOwner}/${GitHubRepo}:ref:refs/heads/main
                token.actions.githubusercontent.com:aud: sts.amazonaws.com

  # IAM Policy for Elastic Beanstalk - scoped to this project's resources
  EBPolicy:
    Type: AWS::IAM::Policy
    Properties:
      PolicyName: !Sub ${RoleName}-EBPolicy
      PolicyDocument:
        Version: 2012-10-17
        Statement:
          # Application-level actions
          - Effect: Allow
            Action:
              - elasticbeanstalk:CreateApplication
              - elasticbeanstalk:UpdateApplication
              - elasticbeanstalk:DeleteApplication
              - elasticbeanstalk:DescribeApplications
            Resource:
              - !Sub arn:aws:elasticbeanstalk:${AWSRegion}:${AWS::AccountId}:application/${EBApplicationName}
          # Environment-level actions
          - Effect: Allow
            Action:
              - elasticbeanstalk:CreateEnvironment
              - elasticbeanstalk:UpdateEnvironment
              - elasticbeanstalk:TerminateEnvironment
              - elasticbeanstalk:DescribeEnvironmentHealth
              - elasticbeanstalk:DescribeEnvironmentResources
              - elasticbeanstalk:RebuildEnvironment
              - elasticbeanstalk:RestartAppServer
            Resource:
              - !Sub arn:aws:elasticbeanstalk:${AWSRegion}:${AWS::AccountId}:environment/${EBApplicationName}/${EBEnvironmentName}
          # Application version actions
          - Effect: Allow
            Action:
              - elasticbeanstalk:CreateApplicationVersion
              - elasticbeanstalk:UpdateApplicationVersion
              - elasticbeanstalk:DeleteApplicationVersion
              - elasticbeanstalk:DescribeApplicationVersions
            Resource:
              - !Sub arn:aws:elasticbeanstalk:${AWSRegion}:${AWS::AccountId}:applicationversion/${EBApplicationName}/*
          # Describe actions scoped to this application via condition key
          # (resource-level ARNs are not supported for these actions, but
          # elasticbeanstalk:InApplication restricts them to this application)
          - Effect: Allow
            Action:
              - elasticbeanstalk:DescribeEnvironments
              - elasticbeanstalk:DescribeEvents
            Resource: "*"
            Condition:
              StringEquals:
                elasticbeanstalk:InApplication: !Sub arn:aws:elasticbeanstalk:${AWSRegion}:${AWS::AccountId}:application/${EBApplicationName}
          # Global read-only actions with no resource or tag context - cannot be restricted further
          - Effect: Allow
            Action:
              - elasticbeanstalk:CheckDNSAvailability
              - elasticbeanstalk:ListAvailableSolutionStacks
            Resource: "*"
          # Allow passing the EB instance profile role and service role to EC2/EB
          - Effect: Allow
            Action:
              - iam:PassRole
            Resource:
              - !Sub arn:aws:iam::${AWS::AccountId}:role/${EBApplicationName}-instance-role
              - !Sub arn:aws:iam::${AWS::AccountId}:role/${EBApplicationName}-service-role
      Roles:
        - !Ref GitHubDeployRole

  # IAM Policy for S3 (limited to deployment bucket)
  S3Policy:
    Type: AWS::IAM::Policy
    Properties:
      PolicyName: !Sub ${RoleName}-S3Policy
      PolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Action:
              - s3:ListBucket
            Resource:
              - !Sub arn:aws:s3:::${S3BucketName}
          - Effect: Allow
            Action:
              - s3:GetObject
              - s3:PutObject
            Resource:
              - !Sub arn:aws:s3:::${S3BucketName}/*
      Roles:
        - !Ref GitHubDeployRole

  # Dedicated execution role that CloudFormation assumes when deploying the
  # infrastructure stack. Carrying IAM/S3/EB creation permissions here keeps
  # them off the GitHub Actions role entirely.
  CFNExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub ${RoleName}-cfn-execution
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Service: cloudformation.amazonaws.com
            Action: sts:AssumeRole
      Policies:
        - PolicyName: CFNExecutionPolicy
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              # IAM: create/manage the EB service role and instance profile
              # defined in cloudformation.yml, scoped to this project's naming pattern
              - Effect: Allow
                Action:
                  - iam:CreateRole
                  - iam:DeleteRole
                  - iam:GetRole
                  - iam:UpdateRole
                  - iam:AttachRolePolicy
                  - iam:DetachRolePolicy
                  - iam:ListRolePolicies
                  - iam:ListAttachedRolePolicies
                  - iam:CreateInstanceProfile
                  - iam:DeleteInstanceProfile
                  - iam:GetInstanceProfile
                  - iam:AddRoleToInstanceProfile
                  - iam:RemoveRoleFromInstanceProfile
                  - iam:ListInstanceProfilesForRole
                  - iam:TagRole
                  - iam:UntagRole
                  - iam:TagInstanceProfile
                  - iam:UntagInstanceProfile
                Resource:
                  - !Sub arn:aws:iam::${AWS::AccountId}:role/${EBApplicationName}-*
                  - !Sub arn:aws:iam::${AWS::AccountId}:instance-profile/${EBApplicationName}-*
              # PassRole: CloudFormation needs to pass the EB roles to EB when
              # creating the environment
              - Effect: Allow
                Action: iam:PassRole
                Resource:
                  - !Sub arn:aws:iam::${AWS::AccountId}:role/${EBApplicationName}-*
              # Allow creation of the EB service-linked role on first use in
              # an account where EB has never been run before
              - Effect: Allow
                Action: iam:CreateServiceLinkedRole
                Resource:
                  - !Sub arn:aws:iam::${AWS::AccountId}:role/aws-service-role/elasticbeanstalk.amazonaws.com/*
              # S3: create and configure the deployment bucket
              - Effect: Allow
                Action:
                  - s3:CreateBucket
                  - s3:DeleteBucket
                  - s3:ListBucket
                  - s3:GetBucketPolicy
                  - s3:PutBucketPolicy
                  - s3:DeleteBucketPolicy
                  - s3:GetEncryptionConfiguration
                  - s3:PutEncryptionConfiguration
                  - s3:GetBucketVersioning
                  - s3:PutBucketVersioning
                  - s3:GetBucketPublicAccessBlock
                  - s3:PutBucketPublicAccessBlock
                Resource:
                  - !Sub arn:aws:s3:::${S3BucketName}
              # EB: manage the application scoped to this project
              - Effect: Allow
                Action:
                  - elasticbeanstalk:CreateApplication
                  - elasticbeanstalk:UpdateApplication
                  - elasticbeanstalk:DeleteApplication
                  - elasticbeanstalk:DescribeApplications
                Resource:
                  - !Sub arn:aws:elasticbeanstalk:${AWSRegion}:${AWS::AccountId}:application/${EBApplicationName}
              # EB: manage the environment
              - Effect: Allow
                Action:
                  - elasticbeanstalk:CreateEnvironment
                  - elasticbeanstalk:UpdateEnvironment
                  - elasticbeanstalk:TerminateEnvironment
                  - elasticbeanstalk:DescribeEnvironmentHealth
                  - elasticbeanstalk:DescribeEnvironmentResources
                Resource:
                  - !Sub arn:aws:elasticbeanstalk:${AWSRegion}:${AWS::AccountId}:environment/${EBApplicationName}/${EBEnvironmentName}
              # EB: describe actions (no resource-level support, restricted by condition)
              - Effect: Allow
                Action:
                  - elasticbeanstalk:DescribeEnvironments
                  - elasticbeanstalk:DescribeEvents
                Resource: "*"
                Condition:
                  StringEquals:
                    elasticbeanstalk:InApplication: !Sub arn:aws:elasticbeanstalk:${AWSRegion}:${AWS::AccountId}:application/${EBApplicationName}
              # EB: global read-only actions that cannot be restricted further
              - Effect: Allow
                Action:
                  - elasticbeanstalk:ListAvailableSolutionStacks
                  - elasticbeanstalk:CheckDNSAvailability
                Resource: "*"

  # IAM Policy for CloudFormation (limited to this stack)
  CloudFormationPolicy:
    Type: AWS::IAM::Policy
    Properties:
      PolicyName: !Sub ${RoleName}-CFNPolicy
      PolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Action:
              - cloudformation:CreateStack
              - cloudformation:UpdateStack
              - cloudformation:DescribeStacks
              - cloudformation:DescribeStackResources
              - cloudformation:GetTemplate
              - cloudformation:ValidateTemplate
              # Change set operations required by `aws cloudformation deploy`
              - cloudformation:CreateChangeSet
              - cloudformation:DescribeChangeSet
              - cloudformation:ExecuteChangeSet
              - cloudformation:DeleteChangeSet
            Resource: !Sub arn:aws:cloudformation:${AWSRegion}:${AWS::AccountId}:stack/${StackName}/*
          # Allow the GitHub Actions role to hand off the execution role to CloudFormation
          - Effect: Allow
            Action: iam:PassRole
            Resource: !GetAtt CFNExecutionRole.Arn
      Roles:
        - !Ref GitHubDeployRole

Outputs:
  GitHubRoleArn:
    Description: ARN of the GitHub Actions role
    Value: !GetAtt GitHubDeployRole.Arn
    Export:
      Name: !Sub ${AWS::StackName}-GitHubRoleArn

  CFNExecutionRoleArn:
    Description: ARN of the CloudFormation execution role (store as AWS_CFN_EXECUTION_ROLE_ARN secret)
    Value: !GetAtt CFNExecutionRole.Arn
    Export:
      Name: !Sub ${AWS::StackName}-CFNExecutionRoleArn
